-- liquibase formatted sql

-- ============================================================================
-- LOOKUP TABLES
-- ============================================================================

-- changeset makers4:schema-001
CREATE TABLE unit_system (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_unit_system_code UNIQUE (code)
);

-- changeset makers4:schema-002
CREATE TABLE material_type (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_material_type_code UNIQUE (code)
);

-- changeset makers4:schema-003
CREATE TABLE cabinet_type (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_cabinet_type_code UNIQUE (code)
);

-- changeset makers4:schema-004
CREATE TABLE face_type (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_face_type_code UNIQUE (code)
);

-- changeset makers4:schema-005
CREATE TABLE toe_kick_style (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_toe_kick_style_code UNIQUE (code)
);

-- changeset makers4:schema-006
CREATE TABLE finished_end_style (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_finished_end_style_code UNIQUE (code)
);

-- changeset makers4:schema-007
CREATE TABLE opening_type (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_opening_type_code UNIQUE (code)
);

-- changeset makers4:schema-008
CREATE TABLE door_style (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_door_style_code UNIQUE (code)
);

-- changeset makers4:schema-009
CREATE TABLE door_panel_style (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_door_panel_style_code UNIQUE (code)
);

-- changeset makers4:schema-010
CREATE TABLE drawer_front_style (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_drawer_front_style_code UNIQUE (code)
);

-- changeset makers4:schema-011
CREATE TABLE edge_profile (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_edge_profile_code UNIQUE (code)
);

-- changeset makers4:schema-012
CREATE TABLE drawer_slide_type (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_drawer_slide_type_code UNIQUE (code)
);

-- changeset makers4:schema-013
CREATE TABLE part_type (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   description TEXT,
   category VARCHAR(60),
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_part_type_code UNIQUE (code)
);

-- changeset makers4:schema-014
CREATE TABLE material (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   code VARCHAR(40) NOT NULL,
   name VARCHAR(100) NOT NULL,
   material_type_id BIGINT NOT NULL,
   species VARCHAR(60),
   thickness_mm INTEGER NOT NULL,
   nominal_thickness VARCHAR(20),
   cost_per_sqft NUMERIC(10,2),
   sort_order INTEGER NOT NULL DEFAULT 0,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_material_code UNIQUE (code)
);

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- changeset makers4:schema-015
CREATE TABLE "user" (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email VARCHAR(255) NOT NULL,
   name VARCHAR(120) NOT NULL,
   password_hash VARCHAR(255) NOT NULL,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_user_email UNIQUE (email)
);

-- changeset makers4:schema-016
CREATE TABLE project (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id BIGINT NOT NULL,
   name VARCHAR(120) NOT NULL,
   description TEXT,
   unit_system_id BIGINT,
   default_box_material_id BIGINT,
   default_back_material_id BIGINT,
   default_face_frame_material_id BIGINT,
   default_door_frame_material_id BIGINT,
   default_door_panel_material_id BIGINT,
   default_drawer_front_material_id BIGINT,
   default_drawer_box_material_id BIGINT,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset makers4:schema-017
CREATE TABLE cabinet (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   project_id BIGINT NOT NULL,
   name VARCHAR(120) NOT NULL,
   description TEXT,
   -- Dimensions
   width_mm INTEGER NOT NULL,
   height_mm INTEGER NOT NULL,
   depth_mm INTEGER NOT NULL,
   -- Construction
   cabinet_type_id BIGINT NOT NULL,
   face_type_id BIGINT NOT NULL,
   -- Toe Kick
   toe_kick_style_id BIGINT NOT NULL,
   toe_kick_height_mm INTEGER,
   toe_kick_depth_mm INTEGER,
   toe_kick_material_id BIGINT,
   -- Box/Carcass
   box_material_id BIGINT,
   back_material_id BIGINT,
   shelf_material_id BIGINT,
   -- Finished Ends
   left_end_finished BOOLEAN NOT NULL DEFAULT FALSE,
   right_end_finished BOOLEAN NOT NULL DEFAULT FALSE,
   back_finished BOOLEAN NOT NULL DEFAULT FALSE,
   finished_end_material_id BIGINT,
   finished_end_style_id BIGINT,
   -- Face Frame
   face_frame_material_id BIGINT,
   face_frame_rail_width_mm INTEGER,
   face_frame_stile_width_mm INTEGER,
   -- Door Defaults
   door_style_id BIGINT,
   door_frame_material_id BIGINT,
   door_panel_style_id BIGINT,
   door_panel_material_id BIGINT,
   door_rail_width_mm INTEGER,
   door_stile_width_mm INTEGER,
   door_groove_depth_mm INTEGER DEFAULT 10,
   door_panel_gap_mm INTEGER DEFAULT 2,
   -- Drawer Front Defaults
   drawer_front_style_id BIGINT,
   drawer_front_material_id BIGINT,
   drawer_front_edge_profile_id BIGINT,
   -- Drawer Box
   drawer_box_material_id BIGINT,
   drawer_box_bottom_material_id BIGINT,
   drawer_slide_type_id BIGINT,
   -- Audit
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset makers4:schema-018
CREATE TABLE cabinet_opening (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cabinet_id BIGINT NOT NULL,
   opening_type_id BIGINT NOT NULL,
   sequence_number INTEGER NOT NULL,
   height_mm INTEGER NOT NULL,
   -- Door Overrides
   door_style_id BIGINT,
   door_frame_material_id BIGINT,
   door_panel_style_id BIGINT,
   door_panel_material_id BIGINT,
   -- Drawer Overrides
   drawer_front_style_id BIGINT,
   drawer_front_material_id BIGINT,
   drawer_front_edge_profile_id BIGINT,
   -- Audit
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ============================================================================
-- DERIVED TABLES
-- ============================================================================

-- changeset makers4:schema-019
CREATE TABLE part (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cabinet_id BIGINT NOT NULL,
   cabinet_opening_id BIGINT,
   part_type_id BIGINT NOT NULL,
   name VARCHAR(120) NOT NULL,
   -- Dimensions
   length_mm INTEGER NOT NULL,
   width_mm INTEGER NOT NULL,
   thickness_mm INTEGER NOT NULL,
   -- Material
   material_id BIGINT NOT NULL,
   quantity INTEGER NOT NULL DEFAULT 1,
   notes TEXT,
   edge_banding_notes VARCHAR(255),
   -- Audit
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset makers4:schema-020
CREATE TABLE cut_list (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   project_id BIGINT,
   cabinet_id BIGINT,
   name VARCHAR(120) NOT NULL,
   generated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset makers4:schema-021
CREATE TABLE cut_list_item (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cut_list_id BIGINT NOT NULL,
   part_id BIGINT NOT NULL,
   sheet_number INTEGER,
   position_x INTEGER,
   position_y INTEGER,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ============================================================================
-- OUTPUT TABLES
-- ============================================================================

-- changeset makers4:schema-022
CREATE TABLE render_job (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   project_id BIGINT,
   cabinet_id BIGINT,
   render_type VARCHAR(40) NOT NULL,
   status VARCHAR(40) NOT NULL,
   requested_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   started_at TIMESTAMP WITHOUT TIME ZONE,
   completed_at TIMESTAMP WITHOUT TIME ZONE,
   error_message TEXT,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset makers4:schema-023
CREATE TABLE render_artifact (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   render_job_id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   artifact_type VARCHAR(40) NOT NULL,
   mime_type VARCHAR(100) NOT NULL,
   file_size_bytes BIGINT,
   file_data BYTEA NOT NULL,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ============================================================================
-- FOREIGN KEYS
-- ============================================================================

-- changeset makers4:schema-024
ALTER TABLE material ADD CONSTRAINT fk_material_material_type FOREIGN KEY (material_type_id) REFERENCES material_type (id);

-- changeset makers4:schema-025
ALTER TABLE project ADD CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES "user" (id);
ALTER TABLE project ADD CONSTRAINT fk_project_unit_system FOREIGN KEY (unit_system_id) REFERENCES unit_system (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_box_material FOREIGN KEY (default_box_material_id) REFERENCES material (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_back_material FOREIGN KEY (default_back_material_id) REFERENCES material (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_face_frame_material FOREIGN KEY (default_face_frame_material_id) REFERENCES material (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_door_frame_material FOREIGN KEY (default_door_frame_material_id) REFERENCES material (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_door_panel_material FOREIGN KEY (default_door_panel_material_id) REFERENCES material (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_drawer_front_material FOREIGN KEY (default_drawer_front_material_id) REFERENCES material (id);
ALTER TABLE project ADD CONSTRAINT fk_project_default_drawer_box_material FOREIGN KEY (default_drawer_box_material_id) REFERENCES material (id);

-- changeset makers4:schema-026
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_project FOREIGN KEY (project_id) REFERENCES project (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_cabinet_type FOREIGN KEY (cabinet_type_id) REFERENCES cabinet_type (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_face_type FOREIGN KEY (face_type_id) REFERENCES face_type (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_toe_kick_style FOREIGN KEY (toe_kick_style_id) REFERENCES toe_kick_style (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_toe_kick_material FOREIGN KEY (toe_kick_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_box_material FOREIGN KEY (box_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_back_material FOREIGN KEY (back_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_shelf_material FOREIGN KEY (shelf_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_finished_end_material FOREIGN KEY (finished_end_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_finished_end_style FOREIGN KEY (finished_end_style_id) REFERENCES finished_end_style (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_face_frame_material FOREIGN KEY (face_frame_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_door_style FOREIGN KEY (door_style_id) REFERENCES door_style (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_door_frame_material FOREIGN KEY (door_frame_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_door_panel_style FOREIGN KEY (door_panel_style_id) REFERENCES door_panel_style (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_door_panel_material FOREIGN KEY (door_panel_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_drawer_front_style FOREIGN KEY (drawer_front_style_id) REFERENCES drawer_front_style (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_drawer_front_material FOREIGN KEY (drawer_front_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_drawer_front_edge_profile FOREIGN KEY (drawer_front_edge_profile_id) REFERENCES edge_profile (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_drawer_box_material FOREIGN KEY (drawer_box_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_drawer_box_bottom_material FOREIGN KEY (drawer_box_bottom_material_id) REFERENCES material (id);
ALTER TABLE cabinet ADD CONSTRAINT fk_cabinet_drawer_slide_type FOREIGN KEY (drawer_slide_type_id) REFERENCES drawer_slide_type (id);

-- changeset makers4:schema-027
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_cabinet FOREIGN KEY (cabinet_id) REFERENCES cabinet (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_opening_type FOREIGN KEY (opening_type_id) REFERENCES opening_type (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_door_style FOREIGN KEY (door_style_id) REFERENCES door_style (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_door_frame_material FOREIGN KEY (door_frame_material_id) REFERENCES material (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_door_panel_style FOREIGN KEY (door_panel_style_id) REFERENCES door_panel_style (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_door_panel_material FOREIGN KEY (door_panel_material_id) REFERENCES material (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_drawer_front_style FOREIGN KEY (drawer_front_style_id) REFERENCES drawer_front_style (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_drawer_front_material FOREIGN KEY (drawer_front_material_id) REFERENCES material (id);
ALTER TABLE cabinet_opening ADD CONSTRAINT fk_cabinet_opening_drawer_front_edge_profile FOREIGN KEY (drawer_front_edge_profile_id) REFERENCES edge_profile (id);

-- changeset makers4:schema-028
ALTER TABLE part ADD CONSTRAINT fk_part_cabinet FOREIGN KEY (cabinet_id) REFERENCES cabinet (id);
ALTER TABLE part ADD CONSTRAINT fk_part_cabinet_opening FOREIGN KEY (cabinet_opening_id) REFERENCES cabinet_opening (id);
ALTER TABLE part ADD CONSTRAINT fk_part_part_type FOREIGN KEY (part_type_id) REFERENCES part_type (id);
ALTER TABLE part ADD CONSTRAINT fk_part_material FOREIGN KEY (material_id) REFERENCES material (id);

-- changeset makers4:schema-029
ALTER TABLE cut_list ADD CONSTRAINT fk_cut_list_project FOREIGN KEY (project_id) REFERENCES project (id);
ALTER TABLE cut_list ADD CONSTRAINT fk_cut_list_cabinet FOREIGN KEY (cabinet_id) REFERENCES cabinet (id);

-- changeset makers4:schema-030
ALTER TABLE cut_list_item ADD CONSTRAINT fk_cut_list_item_cut_list FOREIGN KEY (cut_list_id) REFERENCES cut_list (id);
ALTER TABLE cut_list_item ADD CONSTRAINT fk_cut_list_item_part FOREIGN KEY (part_id) REFERENCES part (id);

-- changeset makers4:schema-031
ALTER TABLE render_job ADD CONSTRAINT fk_render_job_project FOREIGN KEY (project_id) REFERENCES project (id);
ALTER TABLE render_job ADD CONSTRAINT fk_render_job_cabinet FOREIGN KEY (cabinet_id) REFERENCES cabinet (id);

-- changeset makers4:schema-032
ALTER TABLE render_artifact ADD CONSTRAINT fk_render_artifact_render_job FOREIGN KEY (render_job_id) REFERENCES render_job (id);
